server {
  listen 80;
  listen [::]:80;

  server_name web-dev-companion.com www.web-dev-companion.com;
  root /var/www/web-dev-companion;
  index index.html;

  location / {
    try_files $uri $uri/ =404;
  }

  location /assets/ {
    try_files $uri =404;
    access_log off;
    expires 30d;
    add_header Cache-Control "public, max-age=2592000";
  }
}
